name: bloky_dnb_job
on:
  workflow_dispatch:
jobs:
  execute:
    runs-on: ubuntu-latest
    
    steps:
    - name: login to github registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT}}

    - name: print help
      run: | 
        docker run ghcr.io/ktmrmshk/bloky_dnb:latest \
        python /tmp/src/bloky/app_dnb.py --help
      
