name: bloky_dnb_job
on:
  workflow_dispatch:
jobs:
  execute:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ktmrmshk/bloky_dnb:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    steps:
    - name: print help
      run: | 
        docker run ghcr.io/ktmrmshk/bloky_dnb:latest \
        python /tmp/src/bloky/app_dnb.py --help
